### PR TITLE
add query params support

### PR DESCRIPTION
**Pull request by SebastianPozoga**
I added support for unnamed query parameters. I will glad to add it to the repository.
The functionality can be very helpful for a users.

### CODE REVIEW

**Comment by caolan** [comment]
I think in the past I used a different 'connect' compatible middleware to parse querystrings and just placed it in front of dispatch. But now that I look for it I can't find one. I still think it makes sense for dispatch to only match on the path + method and leave any other parsing up to the user. Could you split this out into a separate middleware and do you think that makes sense?

**Comment by SebastianPozoga** [comment]
I am not sure. What do you mean by "separate middleware"? Can you explain?

**Comment by caolan** [comment]
For example: https://github.com/senchalabs/connect - and the middlewares like https://github.com/expressjs/body-parser that will parse the request body.

**Comment by SebastianPozoga** [comment]
Now I am writing set of "WebComponents". Well my case is a little different. I was looking for separated dispatcher (without server). I am implemented routing service on web browser side. I am looking for some simple library like that.

There is service code:
https://github.com/goatcms/goatjs/blob/master/core/services/router.js

And there is very simple test/example:
https://github.com/goatcms/goatjs/blob/master/examples/services/routing/show_query_param.html

If you don't accept my pull request it is ok. Probably my case is new/unexpected way to use your code. I want to providing typical use case.

**Comment by caolan** [comment]
Closing this as out of scope.

**Pull request closed without merging**
